### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by amyquispe** [hoshikoo/HW_03-20#1]
Does not require a Main.java
Generally needs more comments.
Clean, mostly correct code.

Divisor Pattern Art

Very clear.

Twenty Questions

Remove dead code (code that is commented out, unless it's standing for a specific reason, or code that doesn't get reached). The final else is an example of one of these. 

Good exception handling.

Fibonacci

Remove dead code.

Could use some commenting in for-loop block.

A Pretty Title

"char a" might be better named.

Need to handle special cases like like "a", "an", "of."

Verbosity Calculator

Need to complete.

**Comment by hoshikoo** [comment]
I posted another link to the Verbosity Calculator - https://github.com/hoshikoo/VerbCalc.  Can you let me know if I need to work on more?  Thank you, Hoshiko Okii
